services:
  postgres:
    image: postgres:15
    container_name: postgres-gamestudio
    restart: unless-stopped
    environment:
      POSTGRES_DB: gamestudio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-gamestudio
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gamestudio.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - postgres

  api:
    build: .
    container_name: api-gamestudio
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamestudio
      - DB_USER=admin
      - DB_PASSWORD=root
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  postgres_data:
